config/routes.rb
# Rails.application.routes.draw do
#   resources :users
#   resources :subs
#   resources :posts
#   resource :session
# end


Rails.application.routes.draw do
  resources :users do
    resources :posts, only: [:edit, :update]
  end

  resources :subs

  resources :posts, except: [:edit, :update] do
    resources :comments, only: [:new, :create]
  end

  resources :comments, except: [:new]
  resource :session
end

app/models/comment.rb
# == Schema Information
#
# Table name: comments
#
#  id         :integer          not null, primary key
#  content    :text             not null
#  user_id    :integer          not null
#  post_id    :integer          not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Comment < ActiveRecord::Base
  validates :content, :user_id, :post_id, presence: true

  belongs_to :author,
    class_name: :User,
    foreign_key: :user_id

  belongs_to :post


end

app/models/post.rb
# == Schema Information
#
# Table name: posts
#
#  id         :integer          not null, primary key
#  title      :string           not null
#  url        :string
#  content    :text
#  user_id    :integer          not null
#  sub_id     :integer          default("{}"), is an Array
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Post < ActiveRecord::Base
  validates :title, :author, :subs, presence: true

  has_many :post_subs, inverse_of: :post, dependent: :destroy
  has_many :subs, through: :post_subs, source: :sub

  belongs_to :author,
    class_name: :User,
    foreign_key: :user_id

  has_many :comments

  # has_many :postsubs,
  #   class_name: :PostSub
  #
  # has_many :subs,
  #   through: :postsubs,
  #   source: :sub


end

app/models/post_sub.rb
# == Schema Information
#
# Table name: post_subs
#
#  id         :integer          not null, primary key
#  sub_id     :integer          not null
#  post_id    :integer          not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

# class PostSub < ActiveRecord::Base
#   validates :post_id, :sub_id, presence: true
#
#   belongs_to :post
#   belongs_to :sub
# end

class PostSub < ActiveRecord::Base
  validates :post, :sub, presence: true

  belongs_to :post
  belongs_to :sub
end

app/models/sub.rb
# == Schema Information
#
# Table name: subs
#
#  id          :integer          not null, primary key
#  title       :string           not null
#  description :string           not null
#  user_id     :integer          not null
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#

class Sub < ActiveRecord::Base
  validates :title, :description, :moderator, presence: true

  belongs_to :moderator,
    class_name: :User,
    foreign_key: :user_id

  has_many :post_subs,
    class_name: :PostSub,
    inverse_of: :sub,
    dependent: :destroy

  has_many :posts,
    through: :post_subs,
    source: :post
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id              :integer          not null, primary key
#  username        :string           not null
#  password_digest :string           not null
#  session_token   :string           not null
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#

class User < ActiveRecord::Base
  attr_reader :password

  validates :username, :password_digest, :session_token, presence: true
  validates :password, length: { minimum: 6, allow_nil: true }
  validates :username, :session_token, uniqueness: true
  after_initialize :ensure_session_token

  has_many :comments
  has_many :posts

  def self.find_by_credentials(username, password)
    user = User.find_by(username: username)
    user && user.is_valid?(password) ? user : nil
  end

  def reset_session_token!
    self.session_token = SecureRandom.urlsafe_base64(16)
    self.save
    self.session_token
  end

  def ensure_session_token
    self.session_token ||= SecureRandom.urlsafe_base64(16)
  end

  def password=(password)
    @password = password
    self.password_digest = BCrypt::Password.create(password)
  end

  def is_valid?(password)
    BCrypt::Password.new(self.password_digest).is_password?(password)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  helper_method :current_user

  def current_user
    @current_user = User.find_by_session_token(session[:session_token])
  end

  def login
    session[:session_token] = current_user.reset_session_token!
  end

  def logout
    current_user.reset_session_token!
    session[:session_token] = nil
  end

  def logged_in?
    redirect_to new_session_url unless current_user
  end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def new
    @comment = Comment.new
    render :new
  end

  def create
    @comment = Comment.new(comment_params)
    @comment.post_id = @comment.post.id#params[:post_id]
    @comment.user_id = current_user.id
    if @comment.save
      redirect_to post_url(@comment.post_id)
    else
      flash[:errors] = @comment.errors.full_messages
      render :new
    end
  end


  def comment_params
    params.require(:comment).permit(:content)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  before_action :logged_in?

  def new
    @post = Post.new
    render :new
  end

  def create
    @post = Post.new(post_params)

    @post.user_id = current_user.id
    if @post.save!
      redirect_to post_url(@post)
    else
      flash[:errors] = @post.errors.full_messages
      fail
      render :new
    end
  end

  def show
    @post = Post.find_by(id: params[:id])
    render :show
  end

  def edit
    @post = Post.find_by(id: params[:id])
    if @post.user_id == current_user.id
      render :edit
    else
      flash[:errors] = ['You are not the author']
      redirect_to post_url(@post)
    end
  end

  def update
    @post = Post.find_by(id: params[:id])
    if @post.update(post_params)
      redirect_to post_url(@post)
    else
      flash[:errors] = ['Unable to update']
      render :edit
    end
  end

  def destroy
    @post = Post.find_by(id: params[:id])
    redirect_to sub_url(@post.sub_id)
    @post.destroy
  end

  def post_params
    params.require(:post).permit(:title, :url, :content, sub_ids: [])
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
    render :new
  end

  def create
    user = User.find_by_credentials(params[:user][:username], params[:user][:password])
    if user
      session[:session_token] = user.session_token
      redirect_to user_url(user)
    else
      flash[:errors] = ['Invalid credentials']
      render :new
    end
  end

  def destroy
    logout
  end

end

app/controllers/subs_controller.rb
class SubsController < ApplicationController
  before_action :logged_in?

  def index
    @subs = Sub.all
    render :index
  end

  def show
    @sub = Sub.find_by(id: params[:id])
    render :show
  end

  def new
    @sub = Sub.new
    render :new
  end

  def create
    @sub = Sub.new(sub_params)
    @sub.user_id = current_user.id

    if @sub.save
      redirect_to sub_url(@sub)
    else
      flash[:errors] = @sub.errors.full_messages
      render :new
    end
  end

  def edit
    @sub = Sub.find_by(id: params[:id])
    if @sub.user_id == current_user.id
      render :edit
    else
      flash[:errors] = ["Not moderator"]
      redirect_to sub_url(@sub)
    end
  end

  def update
    @sub = Sub.find_by(id: params[:id])

    if @sub.update(sub_params)
      redirect_to sub_url(@sub)
    else
      flash[:errors] = @sub.errors.full_messages
      render :edit
    end
  end

  def sub_params
    params.require(:sub).permit(:title, :description)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
    render :new
  end

  def create
    user = User.new(user_params)
    if user.save
      login
      redirect_to user_url(user)
    else
      flash[:errors] = user.errors.full_messages
      render :new
    end
  end

  def show
    @user = User.find_by(id: params[:id])
    render :show
  end

  def user_params
    params.require(:user).permit(:username, :password)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/subs_helper.rb
module SubsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/new.html.erb
<h1>Add Comment</h1>

<form action="<%= post_comments_url %>" method="post">
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">

  <textarea name="comment[content]" rows="8" cols="80"></textarea>

  <input type="submit" value="Submit">
</form>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Reddit</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

<% if current_user %>
  <%= button_to "Sign Out", session_url, method: :delete %>
<% end %>

app/views/posts/_form.html.erb
<form action="<%= posts_url %>" method="post">
  <% unless action == :new %>
    <input type="hidden" name="_method" value="patch">
  <% end %>
  <input type="hidden" name="authenticity_token" value="<%=             form_authenticity_token %>">

  <label for="title">Title</label>
  <input id='title' type="text" name="post[title]" value='<%= @post.title %>'>

  <br>

  <label for="url">URL</label>
  <input id='url' type="text" name="post[url]" value=' <%= @post.url %>'>

  <br>

  <label for="content">Content</label>
  <textarea id='content' name="post[content]" rows="8" cols="80"><%= @post.content %></textarea>

  <br>

  <label for="sub">Subs</label>
  <!-- <input type="hidden" name="post[sub_id][]" value=""> -->

  <br>

  <% Sub.all.each do |sub_topic| %>
    <label><%= sub_topic.title %>
      <input type="checkbox" name="post[sub_ids][]" value="<%= sub_topic.id %>">
      <%= 'checked' if action != :new && @post.sub_id.include?(sub_topic.id) %>

    </label>
    <br>
  <% end %>

  <input type="submit" value="<%= action == :new ? 'Create' : 'Edit' %> Post">

</form>

app/views/posts/edit.html.erb
<h1>Edit Post</h1>

<%= render "form", action: :edit %>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render "form", action: :new %> 

app/views/posts/show.html.erb
<h1><%= @post.title %></h1>
<br>
<p><%= @post.content %></p>
<br>
<% @post.comments.each do |comment| %>
  <%= comment.content %><br>
  <%= comment.author.username %><br>
<% end %>
<br>
<%= link_to "Add Comment", new_post_comment_url(@post), method: :get %>

app/views/subs/index.html.erb
<h1>Sub-Topics</h1>

<% @subs.each do |sub_topic|%>
  <%= link_to sub_topic.title, sub_url(sub_topic), method: :get %> <br>
<% end %>

<br>

app/views/subs/show.html.erb
<h1><%= @sub.title %></h1>

<% @sub.posts.each do |post| %>
  <%= link_to post.title, post_url(post), method: :get %> <br>
<% end %>

<br>

app/views/users/new.html.erb
<h1>New User</h1>

<form action="<%= users_url %>" method="post">
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">

  <label for="username">Username</label>
  <input id="username" type="text" name="user[username]">

  <label for="password">Password</label>
  <input id="password" type="password" name="user[password]">

  <input type="submit" value="Submit">

</form>

app/views/users/show.html.erb
<h1><%= @user.username %></h1>